/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:701500:
  appc.background(230);
} //_CODE_:window1:701500:

public void slider1_change1(GSlider source, GEvent event) { //_CODE_:Time_Speed:418764:
  println("Time_Speed - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Time_Speed:418764:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 240, 120, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  Time_Speed = new GSlider(window1, 70, 40, 100, 40, 10.0);
  Time_Speed.setLimits(1.0, 0.0, 2.0);
  Time_Speed.setNumberFormat(G4P.DECIMAL, 2);
  Time_Speed.setOpaque(false);
  Time_Speed.addEventHandler(this, "slider1_change1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider Time_Speed; 
